### ISSUE TITLE
Use uname to determine OS instead of passing cmd line argument in install

### ISSUE THREAD

**Issue by hanslovsky** [saalfeldlab/n5-utils#3]
[`uname` works both on Linux and macOS/OSX](https://stackoverflow.com/a/3466183/1725687)
No need for [command line argument](https://github.com/saalfeldlab/n5-utils/blob/master/install#L4)

**Comment by jefferis** [comment]
Yes or since install is a bash script $OSTYPE See e.g. https://stackoverflow.com/questions/394230/how-to-detect-the-os-from-a-bash-script.
 If not would be a good idea to mention the second command line argument in README.

**Comment by jefferis** [comment]
See https://github.com/saalfeldlab/n5-utils/pull/11
