### ISSUE TITLE
n5-copy ignores HDF5 compression

### ISSUE THREAD

**Issue by funkey** [saalfeldlab/n5-utils#5]
Regardless of the compression of an HDF5 dataset, the resulting N5 dataset will have compression type `raw`. This is in contrast to the behavior implied by the command line help:

```
 -c (--compression) VAL     : override compression type of input datasets, e.g.
                              gzip
```

**Comment by axtimwalde** [comment]
This is because I could not find reasonably easy to use API to find out the compression of an HDF5 dataset: https://github.com/saalfeldlab/n5-hdf5/blob/master/src/main/java/org/janelia/saalfeldlab/n5/hdf5/N5HDF5Reader.java#L223 I suggest you use `-c gzip` always.

**Comment by funkey** [comment]
Okay then. I updated the help message to reflect that (https://github.com/saalfeldlab/n5-utils/commit/ebcd9aa0ac95834aab02094d899577f3ddcf66ff).
